spring.application.name=discovery-service

spring.config.import=configserver:http://localhost:9088
spring.cloud.config.fail-fast=true

# eurekaServer thì không c?n ??ng ký v?i chính nó n?a
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
