spring.application.name=discovery-service

spring.config.import=configserver:${CONFIG_SERVER_HOST:http://localhost:9088}
spring.cloud.config.fail-fast=true

# eurekaServer thi khong can dang ky voi chinh no nua
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false
