spring.application.name=client-register-service

#import config from config server
spring.config.import=configserver:http://localhost:9088

# config not start when not read config from server
spring.cloud.config.fail-fast=true