apiVersion: v1
kind: Service
metadata:
  name: discovery-service
  labels:
    app: discovery-service
spec:
  selector:
    app: discovery-service

  ports:
    - port: 9099
      targetPort: 9099

  type: NodePort