server.port=${CLIENT_REGISTER_SERVICE_PORT:9084}

# config database
spring.datasource.username=${DB_USERNAME:root}
spring.datasource.password=${DB_PASSWORD:Anhhuyditu00}
spring.datasource.url=${DB_URL:jdbc:mysql://localhost:3306/springcloud?createDatabaseIfNotExist=true}
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.show-sql=true
spring.jpa.hibernate.ddl-auto=update