server.port=8080
server.servlet.context-path=/

# c?u hình ?? spring cloud gateway t? ??ng ??nh tuy?n t?i các d?ch v? ???c ??ng ký v?i Eureka VD: localhost:8080/ACCOUNT-SERVER/${???ng d?n api}
#spring.cloud.gateway.discovery.locator.enabled=true

#C?u hình ???ng d?n g?i ??n các service
spring.cloud.gateway.routes[0].id=user-route
spring.cloud.gateway.routes[0].uri=lb://account-service
spring.cloud.gateway.routes[0].predicates=Path=/user/**
spring.cloud.gateway.routes[0].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[1].id=report-route
spring.cloud.gateway.routes[1].uri=lb://statistic-service
spring.cloud.gateway.routes[1].predicates=Path=/report/**
spring.cloud.gateway.routes[1].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[2].id=notification-route
spring.cloud.gateway.routes[2].uri=lb://notification-service
spring.cloud.gateway.routes[2].predicates=Path=/notification/**
spring.cloud.gateway.routes[2].filters[0]=StripPrefix=1

spring.cloud.gateway.routes[3].id=openapi
spring.cloud.gateway.routes[3].uri=lb://gateway-service
spring.cloud.gateway.routes[3].predicates=Path=/gateway/**
spring.cloud.gateway.routes[3].filters[0]=StripPrefix=1