server.port=${MONITOR_ADMIN_PORT:9000}
server.servlet.context-path=/

# Mail
spring.mail.default-encoding=UTF-8
spring.mail.host=smtp.gmail.com
spring.mail.username=dinhvanhuy1908202@gmail.com
spring.mail.password=pxkkoabrjadehbls
spring.mail.port=587
spring.mail.protocol=smtp
spring.mail.test-connection=false
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.anable=true
spring.mail.properties.mail.smtp.starttls.required=true

#Email receive notification
spring.boot.admin.notify.mail.enable=true
spring.boot.admin.notify.mail.to=dinhvanhuy1982002@gmail.com